tabla <- read.csv("/home/nicolas/QB9-git/QB9/resources/dataframesinesp.csv", header = TRUE, sep = ",", quote = "\"")
linea <- lm(tabla$Decay ~ tabla$Lonely.PTM)
plot(x=tabla$Lonely.PTM,y=tabla$Decay, main = "Lonely Decay", pch = 21, bg = "red", xlab="Solo PTMs", ylab="Decay")
abline(linea$coefficients)
text(tabla$Lonely.PTM, tabla$Decay, tabla$Residue, pos = 4, offset = 0.25, cex = 0.7)
