tabla <- read.csv("/home/nicolas/QB9-git/QB9/resources/dataframesinesp.csv", header = TRUE, sep = ",", quote = "\"")
linea <- lm(tabla$Nucleophilicity ~ tabla$Total.PTM)
plot(x=tabla$Total.PTM,y=tabla$Nucleophilicity, main = "Total Decay", pch = 21, bg = "red", xlab="Tot PTMs", ylab="Decay")
abline(linea$coefficients)
text(tabla$Total.PTM, tabla$Nucleophilicity, tabla$Residue, pos = 4, offset = 0.25, cex = 0.7)
summary(linea)
anova(linea)
multRegress(XX=as.matrix(tabla$Total.PTM), yy=as.matrix(tabla$Decay), nperm = 10000000)